FROM PREVIOUS_IMAGE

# RUN apt-get install --yes \
#  clang

# TODO: Actually download and compile and install Zap-CC, preferably with the
# "temporary Docker image" paradigm.

ENV CC="zapcc"
ENV CXX="zapcc++"
